#!/bin/bash

if [ -z "$MYSQL_ENV_MYSQL_USER" ]; then echo "Error: MYSQL_ENV_MYSQL_USER not set"; echo "Finished: FAILURE"; exit 1; fi
if [ -z "$MYSQL_ENV_MYSQL_DATABASE" ]; then echo "Error: MYSQL_ENV_MYSQL_DATABASE not set"; echo "Finished: FAILURE"; exit 1; fi
if [ -z "$MYSQL_ENV_MYSQL_PASSWORD" ]; then echo "Error: MYSQL_ENV_MYSQL_PASSWORD not set"; echo "Finished: FAILURE"; exit 1; fi

BASE_DIR=/var/www/html/wp-content
DIRS_TO_BKP=(uploads)

TAR_PATH=/backups/backup_`date '+%Y%m%d'`.tar
for d in ${DIRS_TO_BKP[*]}
do
    if [ -d $BASE_DIR/$d ]
    then
        echo 'creating backup archive of '$BASE_DIR/$d
        tar  --append  -vv --directory="$BASE_DIR" --file="$TAR_PATH" "./$d"
    fi
done
gzip --force $TAR_PATH

echo 'creating database dump'
mysqldump -h $DB_HOST --add-drop-table -u$MYSQL_ENV_MYSQL_USER -p $MYSQL_ENV_MYSQL_DATABASE --password=$MYSQL_ENV_MYSQL_PASSWORD | bzip2 -c > /backups/backup_`date '+%Y%m%d'`.sql.bz2

echo 'Finished: SUCCESS'
